#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =  -Iinclude -I.
CFLAGS =  -std=c++0x -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB =  -lmongoclient -lfcgi -lsphinxclient -lGeoIP -lrabbitmq -lboost_date_time -lboost_regex -lboost_filesystem -lboost_thread -lboost_system -licui18n -licuuc -licudata -ltinyxml -lsqlite3 -lpthread
LDFLAGS =  /usr/local/lib/libamqpcpp.a

INC_DEBUG =  $(INC) -Iinclude -I../libredis/
CFLAGS_DEBUG =  $(CFLAGS) -g -DDEBUG
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB) ../libredis/lib/libredis.a -lrt
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/getmyad

INC_RELEASE =  $(INC) -Iinclude -I../libredis
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB) ../libredis/lib/libredis.a -lrt
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/getmyad

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/GeoRerions.o $(OBJDIR_DEBUG)/src/GeoIPTools.o $(OBJDIR_DEBUG)/src/EBranch.o $(OBJDIR_DEBUG)/src/DataBase.o $(OBJDIR_DEBUG)/src/DB.o $(OBJDIR_DEBUG)/src/Core.o $(OBJDIR_DEBUG)/src/Cookie.o $(OBJDIR_DEBUG)/src/Config.o $(OBJDIR_DEBUG)/src/CgiService.o $(OBJDIR_DEBUG)/src/Campaign.o $(OBJDIR_DEBUG)/src/BaseCore.o $(OBJDIR_DEBUG)/src/HistoryManager.o $(OBJDIR_DEBUG)/src/Params.o $(OBJDIR_DEBUG)/src/sphinxRequests.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/json.o $(OBJDIR_DEBUG)/src/base64.o $(OBJDIR_DEBUG)/src/XXXSearcher.o $(OBJDIR_DEBUG)/src/UrlParser.o $(OBJDIR_DEBUG)/src/Server.o $(OBJDIR_DEBUG)/src/RedisClient.o $(OBJDIR_DEBUG)/src/ParentDB.o $(OBJDIR_DEBUG)/src/ParamParse.o $(OBJDIR_DEBUG)/src/Offer.o $(OBJDIR_DEBUG)/src/Log.o $(OBJDIR_DEBUG)/src/KompexSQLiteStatement.o $(OBJDIR_DEBUG)/src/KompexSQLiteDatabase.o $(OBJDIR_DEBUG)/src/InformerTemplate.o $(OBJDIR_DEBUG)/src/Informer.o $(OBJDIR_DEBUG)/src/HistoryManagerShortTerm.o $(OBJDIR_DEBUG)/src/HistoryManagerRetargeting.o $(OBJDIR_DEBUG)/src/HistoryManagerOffer.o $(OBJDIR_DEBUG)/src/HistoryManagerLongTerm.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/GeoRerions.o $(OBJDIR_RELEASE)/src/GeoIPTools.o $(OBJDIR_RELEASE)/src/EBranch.o $(OBJDIR_RELEASE)/src/DataBase.o $(OBJDIR_RELEASE)/src/DB.o $(OBJDIR_RELEASE)/src/Core.o $(OBJDIR_RELEASE)/src/Cookie.o $(OBJDIR_RELEASE)/src/Config.o $(OBJDIR_RELEASE)/src/CgiService.o $(OBJDIR_RELEASE)/src/Campaign.o $(OBJDIR_RELEASE)/src/BaseCore.o $(OBJDIR_RELEASE)/src/HistoryManager.o $(OBJDIR_RELEASE)/src/Params.o $(OBJDIR_RELEASE)/src/sphinxRequests.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/json.o $(OBJDIR_RELEASE)/src/base64.o $(OBJDIR_RELEASE)/src/XXXSearcher.o $(OBJDIR_RELEASE)/src/UrlParser.o $(OBJDIR_RELEASE)/src/Server.o $(OBJDIR_RELEASE)/src/RedisClient.o $(OBJDIR_RELEASE)/src/ParentDB.o $(OBJDIR_RELEASE)/src/ParamParse.o $(OBJDIR_RELEASE)/src/Offer.o $(OBJDIR_RELEASE)/src/Log.o $(OBJDIR_RELEASE)/src/KompexSQLiteStatement.o $(OBJDIR_RELEASE)/src/KompexSQLiteDatabase.o $(OBJDIR_RELEASE)/src/InformerTemplate.o $(OBJDIR_RELEASE)/src/Informer.o $(OBJDIR_RELEASE)/src/HistoryManagerShortTerm.o $(OBJDIR_RELEASE)/src/HistoryManagerRetargeting.o $(OBJDIR_RELEASE)/src/HistoryManagerOffer.o $(OBJDIR_RELEASE)/src/HistoryManagerLongTerm.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/GeoRerions.o: src/GeoRerions.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GeoRerions.cpp -o $(OBJDIR_DEBUG)/src/GeoRerions.o

$(OBJDIR_DEBUG)/src/GeoIPTools.o: src/GeoIPTools.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/GeoIPTools.cpp -o $(OBJDIR_DEBUG)/src/GeoIPTools.o

$(OBJDIR_DEBUG)/src/EBranch.o: src/EBranch.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/EBranch.cpp -o $(OBJDIR_DEBUG)/src/EBranch.o

$(OBJDIR_DEBUG)/src/DataBase.o: src/DataBase.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DataBase.cpp -o $(OBJDIR_DEBUG)/src/DataBase.o

$(OBJDIR_DEBUG)/src/DB.o: src/DB.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DB.cpp -o $(OBJDIR_DEBUG)/src/DB.o

$(OBJDIR_DEBUG)/src/Core.o: src/Core.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Core.cpp -o $(OBJDIR_DEBUG)/src/Core.o

$(OBJDIR_DEBUG)/src/Cookie.o: src/Cookie.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Cookie.cpp -o $(OBJDIR_DEBUG)/src/Cookie.o

$(OBJDIR_DEBUG)/src/Config.o: src/Config.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Config.cpp -o $(OBJDIR_DEBUG)/src/Config.o

$(OBJDIR_DEBUG)/src/CgiService.o: src/CgiService.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/CgiService.cpp -o $(OBJDIR_DEBUG)/src/CgiService.o

$(OBJDIR_DEBUG)/src/Campaign.o: src/Campaign.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Campaign.cpp -o $(OBJDIR_DEBUG)/src/Campaign.o

$(OBJDIR_DEBUG)/src/BaseCore.o: src/BaseCore.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BaseCore.cpp -o $(OBJDIR_DEBUG)/src/BaseCore.o

$(OBJDIR_DEBUG)/src/HistoryManager.o: src/HistoryManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/HistoryManager.cpp -o $(OBJDIR_DEBUG)/src/HistoryManager.o

$(OBJDIR_DEBUG)/src/Params.o: src/Params.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Params.cpp -o $(OBJDIR_DEBUG)/src/Params.o

$(OBJDIR_DEBUG)/src/sphinxRequests.o: src/sphinxRequests.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/sphinxRequests.cpp -o $(OBJDIR_DEBUG)/src/sphinxRequests.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/json.o: src/json.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/json.cpp -o $(OBJDIR_DEBUG)/src/json.o

$(OBJDIR_DEBUG)/src/base64.o: src/base64.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/base64.cpp -o $(OBJDIR_DEBUG)/src/base64.o

$(OBJDIR_DEBUG)/src/XXXSearcher.o: src/XXXSearcher.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/XXXSearcher.cpp -o $(OBJDIR_DEBUG)/src/XXXSearcher.o

$(OBJDIR_DEBUG)/src/UrlParser.o: src/UrlParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/UrlParser.cpp -o $(OBJDIR_DEBUG)/src/UrlParser.o

$(OBJDIR_DEBUG)/src/Server.o: src/Server.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Server.cpp -o $(OBJDIR_DEBUG)/src/Server.o

$(OBJDIR_DEBUG)/src/RedisClient.o: src/RedisClient.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RedisClient.cpp -o $(OBJDIR_DEBUG)/src/RedisClient.o

$(OBJDIR_DEBUG)/src/ParentDB.o: src/ParentDB.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ParentDB.cpp -o $(OBJDIR_DEBUG)/src/ParentDB.o

$(OBJDIR_DEBUG)/src/ParamParse.o: src/ParamParse.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ParamParse.cpp -o $(OBJDIR_DEBUG)/src/ParamParse.o

$(OBJDIR_DEBUG)/src/Offer.o: src/Offer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Offer.cpp -o $(OBJDIR_DEBUG)/src/Offer.o

$(OBJDIR_DEBUG)/src/Log.o: src/Log.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Log.cpp -o $(OBJDIR_DEBUG)/src/Log.o

$(OBJDIR_DEBUG)/src/KompexSQLiteStatement.o: src/KompexSQLiteStatement.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/KompexSQLiteStatement.cpp -o $(OBJDIR_DEBUG)/src/KompexSQLiteStatement.o

$(OBJDIR_DEBUG)/src/KompexSQLiteDatabase.o: src/KompexSQLiteDatabase.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/KompexSQLiteDatabase.cpp -o $(OBJDIR_DEBUG)/src/KompexSQLiteDatabase.o

$(OBJDIR_DEBUG)/src/InformerTemplate.o: src/InformerTemplate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/InformerTemplate.cpp -o $(OBJDIR_DEBUG)/src/InformerTemplate.o

$(OBJDIR_DEBUG)/src/Informer.o: src/Informer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Informer.cpp -o $(OBJDIR_DEBUG)/src/Informer.o

$(OBJDIR_DEBUG)/src/HistoryManagerShortTerm.o: src/HistoryManagerShortTerm.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/HistoryManagerShortTerm.cpp -o $(OBJDIR_DEBUG)/src/HistoryManagerShortTerm.o

$(OBJDIR_DEBUG)/src/HistoryManagerRetargeting.o: src/HistoryManagerRetargeting.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/HistoryManagerRetargeting.cpp -o $(OBJDIR_DEBUG)/src/HistoryManagerRetargeting.o

$(OBJDIR_DEBUG)/src/HistoryManagerOffer.o: src/HistoryManagerOffer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/HistoryManagerOffer.cpp -o $(OBJDIR_DEBUG)/src/HistoryManagerOffer.o

$(OBJDIR_DEBUG)/src/HistoryManagerLongTerm.o: src/HistoryManagerLongTerm.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/HistoryManagerLongTerm.cpp -o $(OBJDIR_DEBUG)/src/HistoryManagerLongTerm.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/GeoRerions.o: src/GeoRerions.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GeoRerions.cpp -o $(OBJDIR_RELEASE)/src/GeoRerions.o

$(OBJDIR_RELEASE)/src/GeoIPTools.o: src/GeoIPTools.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/GeoIPTools.cpp -o $(OBJDIR_RELEASE)/src/GeoIPTools.o

$(OBJDIR_RELEASE)/src/EBranch.o: src/EBranch.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/EBranch.cpp -o $(OBJDIR_RELEASE)/src/EBranch.o

$(OBJDIR_RELEASE)/src/DataBase.o: src/DataBase.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DataBase.cpp -o $(OBJDIR_RELEASE)/src/DataBase.o

$(OBJDIR_RELEASE)/src/DB.o: src/DB.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DB.cpp -o $(OBJDIR_RELEASE)/src/DB.o

$(OBJDIR_RELEASE)/src/Core.o: src/Core.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Core.cpp -o $(OBJDIR_RELEASE)/src/Core.o

$(OBJDIR_RELEASE)/src/Cookie.o: src/Cookie.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Cookie.cpp -o $(OBJDIR_RELEASE)/src/Cookie.o

$(OBJDIR_RELEASE)/src/Config.o: src/Config.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Config.cpp -o $(OBJDIR_RELEASE)/src/Config.o

$(OBJDIR_RELEASE)/src/CgiService.o: src/CgiService.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/CgiService.cpp -o $(OBJDIR_RELEASE)/src/CgiService.o

$(OBJDIR_RELEASE)/src/Campaign.o: src/Campaign.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Campaign.cpp -o $(OBJDIR_RELEASE)/src/Campaign.o

$(OBJDIR_RELEASE)/src/BaseCore.o: src/BaseCore.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BaseCore.cpp -o $(OBJDIR_RELEASE)/src/BaseCore.o

$(OBJDIR_RELEASE)/src/HistoryManager.o: src/HistoryManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/HistoryManager.cpp -o $(OBJDIR_RELEASE)/src/HistoryManager.o

$(OBJDIR_RELEASE)/src/Params.o: src/Params.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Params.cpp -o $(OBJDIR_RELEASE)/src/Params.o

$(OBJDIR_RELEASE)/src/sphinxRequests.o: src/sphinxRequests.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/sphinxRequests.cpp -o $(OBJDIR_RELEASE)/src/sphinxRequests.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/json.o: src/json.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/json.cpp -o $(OBJDIR_RELEASE)/src/json.o

$(OBJDIR_RELEASE)/src/base64.o: src/base64.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/base64.cpp -o $(OBJDIR_RELEASE)/src/base64.o

$(OBJDIR_RELEASE)/src/XXXSearcher.o: src/XXXSearcher.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/XXXSearcher.cpp -o $(OBJDIR_RELEASE)/src/XXXSearcher.o

$(OBJDIR_RELEASE)/src/UrlParser.o: src/UrlParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/UrlParser.cpp -o $(OBJDIR_RELEASE)/src/UrlParser.o

$(OBJDIR_RELEASE)/src/Server.o: src/Server.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Server.cpp -o $(OBJDIR_RELEASE)/src/Server.o

$(OBJDIR_RELEASE)/src/RedisClient.o: src/RedisClient.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RedisClient.cpp -o $(OBJDIR_RELEASE)/src/RedisClient.o

$(OBJDIR_RELEASE)/src/ParentDB.o: src/ParentDB.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ParentDB.cpp -o $(OBJDIR_RELEASE)/src/ParentDB.o

$(OBJDIR_RELEASE)/src/ParamParse.o: src/ParamParse.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ParamParse.cpp -o $(OBJDIR_RELEASE)/src/ParamParse.o

$(OBJDIR_RELEASE)/src/Offer.o: src/Offer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Offer.cpp -o $(OBJDIR_RELEASE)/src/Offer.o

$(OBJDIR_RELEASE)/src/Log.o: src/Log.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Log.cpp -o $(OBJDIR_RELEASE)/src/Log.o

$(OBJDIR_RELEASE)/src/KompexSQLiteStatement.o: src/KompexSQLiteStatement.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/KompexSQLiteStatement.cpp -o $(OBJDIR_RELEASE)/src/KompexSQLiteStatement.o

$(OBJDIR_RELEASE)/src/KompexSQLiteDatabase.o: src/KompexSQLiteDatabase.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/KompexSQLiteDatabase.cpp -o $(OBJDIR_RELEASE)/src/KompexSQLiteDatabase.o

$(OBJDIR_RELEASE)/src/InformerTemplate.o: src/InformerTemplate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/InformerTemplate.cpp -o $(OBJDIR_RELEASE)/src/InformerTemplate.o

$(OBJDIR_RELEASE)/src/Informer.o: src/Informer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Informer.cpp -o $(OBJDIR_RELEASE)/src/Informer.o

$(OBJDIR_RELEASE)/src/HistoryManagerShortTerm.o: src/HistoryManagerShortTerm.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/HistoryManagerShortTerm.cpp -o $(OBJDIR_RELEASE)/src/HistoryManagerShortTerm.o

$(OBJDIR_RELEASE)/src/HistoryManagerRetargeting.o: src/HistoryManagerRetargeting.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/HistoryManagerRetargeting.cpp -o $(OBJDIR_RELEASE)/src/HistoryManagerRetargeting.o

$(OBJDIR_RELEASE)/src/HistoryManagerOffer.o: src/HistoryManagerOffer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/HistoryManagerOffer.cpp -o $(OBJDIR_RELEASE)/src/HistoryManagerOffer.o

$(OBJDIR_RELEASE)/src/HistoryManagerLongTerm.o: src/HistoryManagerLongTerm.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/HistoryManagerLongTerm.cpp -o $(OBJDIR_RELEASE)/src/HistoryManagerLongTerm.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

