#! /bin/sh
### BEGIN INIT INFO
# Provides:	        keywords-indexcreator
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:    keywords-indexcreator
# Description:      keywords-indexcreator for RG (getmyad-worker)
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/workerd
DAEMON_ARGS="-c /etc/workerd/config-workerd.xml"
NAME=workerd
DESC=workerd
RUNDIR=/run/workerd
PIDFILE=$RUNDIR/pid
SOKET=$RUNDIR/sock
USER=www-data
GROUP=www-data

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
    mkdir -p $RUNDIR
    chown -R $USER:$GROUP $RUNDIR
	touch $PIDFILE
	chown $USER:$GROUP $PIDFILE
    if [ -f $SOKET ]
    then
        rm $SOKET
    fi
	if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid $USER:$GROUP --exec $DAEMON -- $DAEMON_ARGS
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
